### ISSUE TITLE
'CondaVerificationError' and 'ClobberError'

### ISSUE THREAD

**Issue by chencan-cc** [bio-miga/miga#103]
Hi, all,
I was using conda to install MiGA on a local MasOS laptop. When I used conda to activate MiGA and following install the requirements, it always reported 'CondaVerificationError' and 'ClobberError'.
The description attached,
[The errors.txt](https://github.com/bio-miga/miga/files/4794476/The.errors.txt)
I was trying to reinstall conda with different versions, or use a command 'conda clean -a'
to reset conda, but the errors were still reporting.

**Comment by lmrodriguezr** [comment]
Hello @chencan-cc 

I strongly recommend using Homebrew whenever possible, since `conda` has incompatibilities between packages that are very system-specific.  However, I have now updated the instructions to resolve some incompatibilities between conda packages.

It seems the conda package for FastANI still downgrades several other packages, so I would recommend excluding FastANI from the conda installation and installing it directly from source or through Homebrew. Nevertheless, If you're ok with the risk of using (very) outdated packages, I believe the new instructions should work properly.

I'm closing this issue, but please feel free to reopen if you continue to experience problems.
