### ISSUE TITLE
Quality (essential genes) only reporting for 23 essential genes

### ISSUE THREAD

**Issue by kkowalden** [bio-miga/miga#160]
Hello,

We have recently noticed that under the "Full Report" tab of the **Quality (essential genes)** section, the fraction of essential genes reported is out of 23, instead of the 106 or 111 from the DuPont set.

However, if the "collection" link is followed, the **log** file tab does show the fraction of essential genes out of 111.

Thanks,
Kim

**Comment by lmrodriguezr** [comment]
Dear Kim,

Thank you for your report! Indeed, this was a necessary change in order to support unannotated archaeal input (see #157), but we're actively working on extending the set back for all prokaryotes. This is a top development priority right after we produce the `2023-04` database releases.

Best wishes,
Miguel.
